### ISSUE TITLE
Tailwind and exported css

### ISSUE THREAD

**Issue by niktek** [sw-yx/sveltekit-monorepo#2]
Hi,

Just wondering if you have solved things like let's say the UI project utilising the tailwind plugin and the dashboard consuming the components from UI.  At lest in dev mode, I find that the dashboard project won't receive the tailwind classes until I publish the UI package to get the appropriate TW classes generated and exported.

Any ideas or pointers to how one might work around this ?

Cheers,
Nik

**Comment by niktek** [comment]
Figured it out with some more monorepo videos

**Comment by swyxio** [comment]
next time try to drop the videos so you help others :) 

![image](https://user-images.githubusercontent.com/6764957/203964275-cc3a1d47-2813-42be-b444-7127b52a0ead.png)
